WIP: Add option to disable SSL verification in requests
inglesp/http-crawler pull request #17
Opened 2018-03-26 23:21 UTC by keaneokelley

This PR adds the ability to disable SSL verification for requests against servers with an invalid SSL configuration or self-signed certificates.

I began writing some tests, although I am looking for suggestions on how to proceed with them in the cleanest way. Right now, they are a bit broken.

2018-03-28 08:05 UTC, inglesp commented
Hi

2018-06-11 12:15 UTC, inglesp commented
Hi @keaneokelley 

I have no idea what happened to my comment in March!

Thanks for this PR -- it's a good addition.

As for testing, I think all you need to test is that in the case that a server has a bad certificate, requesting a page over SSL fails when `verify=True` and succeeds when `verify=False` -- so you don't need to serve the whole of the `site/` directory over SSL (that way, I think you'll have problems with the `http://` in the links).

Instead, you should create a new directory at `tests/one-page-site/` containing just an `index.html` that has no links.

Then, in `serve()` you should change `_serve()` so that it takes an `bad_ssl_cert` argument which can be `True` or `False` (the default).  If `False`, it should do what we currently do; if `True` it should do the `ssl.wrap_socket()` stuff, with a bad SSL certificate.

`serve()` should then start another process on port 8002, serving the `one-page-site` site with a bad SSL certificate.  You can then test that `verify=True` / `verify=False` does what you expect.

Does that make sense?

2018-06-13 18:44 UTC, keaneokelley commented
Thanks for the suggestions, I think I was able to implement it.

Only problem, the tests for Python 3.4 are not passing and I've not figured out why.

2018-06-14 11:28 UTC, inglesp requested changes
Thanks!

I've left one comment, and I haven't dug into the test failure.  I'm about to go on holiday for a few days, but will investigate once I'm back if you haven't managed to track down the problem.

2018-06-14 11:28 UTC, inglesp commented on tests/test_http_crawler.py
> +    assert e
You should use [`pytest.raises`](http://pytest.readthedocs.io/en/reorganize-docs/new-docs/user/pytest_raises.html) here.

2018-06-20 15:23 UTC, inglesp commented
Thanks for the update.

The problem with the tests is that `ssl.PROTOCOL_TLS` is not defined in Python 3.4.  I suggest dropping the `ssl_version` argument and seeing what happens -- it looks like Python provides a sensible default and doing so works for 3.4 and 3.6.

(If you're interested, I managed to work this out by running just the failing test with `python -m pytest tests/test_http_crawler.py::test_ssl_verify_false` and this included a helpful traceback in the output.)

2018-06-24 22:59 UTC, keaneokelley commented
Should be passing now. The only thing that is failing (coverage-report) fails on master as well.

2018-06-29 14:04 UTC, inglesp commented
The failing tests were (I think) caused by flakiness in the tests themselves, and re-running them has turned Travis green.  (This may also be why the cause of failures on 3.4 weren't obvious.)

Thanks for your work on this!

2018-06-29 14:04 UTC, inglesp approved these changes

2018-06-29 14:04 UTC, merged